export const ErrorConstants = {
  PASSWORD_IS_REQUIRED: "Password is required.",
  ADMIN_ALREADY_EXISTS: "Admin Already Exits",
  LOGIN_ID_AND_PASSWORD_ARE_REQUIRED: "Login ID and password are required.",
  INVALID_LOGIN_ID_OR_PASSWORD: "Invalid login ID or password.",
  PLEASE_PROVIDE_VALID_DETAILS: "Please provide valid details ...!",
  TOKEN_NOT_FOUND: "token not found ...!",
  EXPIRED_OTP: "OTP has expired ...!",
  INVALID_OTP: "Invalid OTP ...!",
  INVALID_EMAIL: "Invalid email ...!",
  INVALID_MOBILE: "Invalid mobile number ...!",
  INVALID_REFRESH_TOKEN: "Invalid refresh token ...!",
  INVALID_OR_EXPIRE_TOKEN: "Invalid or expired token",
  FIRM_CREATION_FAILED: "Firm creation failed ...!",
  PATH_NOT_FOUND: "path not found ..!",
};
