export const ErrorConstants = {
  BAD_REQUEST: 400,
  BAD_REQUEST_MESSAGE: "Bad request",
  UNAUTHORIZED: 401,
  UNAUTHORIZED_MESSAGE: "Unauthorized",
  FORBIDDEN: 403,
  FORBIDDEN_MESSAGE: "Forbidden",
  NOT_FOUND: 404,
  NOT_FOUND_MESSAGE: "Not found",
  METHOD_NOT_ALLOWED: 405,
  METHOD_NOT_ALLOWED_MESSAGE: "Method not allowed",
  CONFLICT: 409,
  CONFLICT_MESSAGE: "Conflict",
  UNPROCESSABLE_ENTITY: 422,
  UNPROCESSABLE_ENTITY_MESSAGE: "Unprocessable entity",
  TOO_MANY_REQUESTS: 429,
  TOO_MANY_REQUESTS_MESSAGE: "Too many requests",
  INTERNAL_SERVER_ERROR: 500,
  INTERNAL_SERVER_ERROR_MESSAGE: "An unknown error occurred: Internal server error",
  BAD_GATEWAY: 502,
  BAD_GATEWAY_MESSAGE: "Bad gateway",
  SERVICE_UNAVAILABLE: 503,
  SERVICE_UNAVAILABLE_MESSAGE: "Service unavailable",
  GATEWAY_TIMEOUT: 504,
  GATEWAY_TIMEOUT_MESSAGE: "Gateway timeout",

  FILE_UPLOAD_ERROR_MESSAGE: "Something wrong with file, Please check ...!",
  DUPLICATE_ENTRY_MESSAGE: "Duplicate entry: ",
  FOREIGN_KEY_CONSTRAINT_MESSAGE: "Foreign key constraint failed on field: ",
  RECORD_NOT_FOUND_MESSAGE: "Record not found: ",
  VALIDATION_ERROR_MESSAGE: "Validation error",
  INITIALIZATION_ERROR_MESSAGE: "Initialization error",
  UNEXPECTED_PRISMA_ERROR_MESSAGE: "Unexpected Prisma error: ",

  // Prisma Error Codes
  ERROR_CODE_DUPLICATE_ENTRY: "P2002",
  ERROR_CODE_FOREIGN_KEY_CONSTRAINT: "P2003",
  ERROR_CODE_RECORD_NOT_FOUND: "P2025",
};
